"""added email to user

Revision ID: 35f7b24c9fdf
Revises: 064707387770
Create Date: 2023-03-14 16:02:48.442293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35f7b24c9fdf"
down_revision = "064707387770"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
